import { useState } from "react";
import { Languages, AlertTriangle, ChevronDown, ChevronUp } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Collapsible, CollapsibleContent, CollapsibleTrigger } from "@/components/ui/collapsible";
import { Skeleton } from "@/components/ui/skeleton";
import { usePublishedTranslation } from "@/hooks/usePlainLanguageTranslations";
import ReactMarkdown from "react-markdown";

interface PlainLanguageViewProps {
  contentType: "article" | "recital";
  contentId: number;
  originalContent: React.ReactNode;
}

const PlainLanguageView = ({
  contentType,
  contentId,
  originalContent,
}: PlainLanguageViewProps) => {
  const [showPlainLanguage, setShowPlainLanguage] = useState(false);
  const { data: translation, isLoading } = usePublishedTranslation(contentType, contentId);

  if (isLoading) {
    return (
      <div className="space-y-4">
        {originalContent}
        <Skeleton className="h-10 w-48" />
      </div>
    );
  }

  // If no translation exists, just show original content
  if (!translation) {
    return <>{originalContent}</>;
  }

  return (
    <div className="space-y-4">
      {/* Toggle Button */}
      <div className="flex items-center gap-2">
        <Button
          variant={showPlainLanguage ? "default" : "outline"}
          size="sm"
          onClick={() => setShowPlainLanguage(!showPlainLanguage)}
          className="gap-2"
        >
          <Languages className="h-4 w-4" />
          {showPlainLanguage ? "Hide" : "Show"} Plain Language Version
        </Button>
        {showPlainLanguage && (
          <Badge variant="secondary" className="text-xs">
            AI-Generated
          </Badge>
        )}
      </div>

      {/* Side-by-side view when enabled */}
      {showPlainLanguage ? (
        <div className="grid lg:grid-cols-2 gap-6">
          {/* Original Legal Text */}
          <Card className="border-primary/20">
            <CardHeader className="pb-3">
              <CardTitle className="text-sm font-medium flex items-center gap-2">
                <span className="w-2 h-2 rounded-full bg-primary" />
                Legal Text
              </CardTitle>
            </CardHeader>
            <CardContent className="prose prose-sm dark:prose-invert max-w-none">
              {originalContent}
            </CardContent>
          </Card>

          {/* Plain Language Version */}
          <Card className="border-green-500/20 bg-green-50/50 dark:bg-green-950/10">
            <CardHeader className="pb-3">
              <CardTitle className="text-sm font-medium flex items-center gap-2">
                <span className="w-2 h-2 rounded-full bg-green-500" />
                Plain Language
              </CardTitle>
            </CardHeader>
            <CardContent>
              <div className="prose prose-sm dark:prose-invert max-w-none">
                <ReactMarkdown>{translation.plain_language_text}</ReactMarkdown>
              </div>
              
              {/* Disclaimer */}
              <Collapsible className="mt-4">
                <CollapsibleTrigger asChild>
                  <Button variant="ghost" size="sm" className="w-full justify-between text-xs text-muted-foreground hover:text-foreground p-2 h-auto">
                    <span className="flex items-center gap-1">
                      <AlertTriangle className="h-3 w-3" />
                      AI Disclaimer
                    </span>
                    <ChevronDown className="h-3 w-3 transition-transform group-data-[state=open]:rotate-180" />
                  </Button>
                </CollapsibleTrigger>
                <CollapsibleContent>
                  <div className="text-xs text-muted-foreground bg-muted/50 rounded-lg p-3 mt-2">
                    <p className="font-medium mb-1">Important Notice</p>
                    <p>
                      This plain language version was generated by AI and is provided for 
                      informational purposes only. It may contain inaccuracies or omissions. 
                      For legal purposes, always refer to the official legal text. This 
                      simplified version is not a substitute for legal advice.
                    </p>
                  </div>
                </CollapsibleContent>
              </Collapsible>
            </CardContent>
          </Card>
        </div>
      ) : (
        // Just the original content when plain language is hidden
        <>{originalContent}</>
      )}
    </div>
  );
};

export default PlainLanguageView;
